const urls = {
    LOCAL_URL_FOR_PHYSICAL_DEVICE: 'http://192.168.1.21:3001',
    LOCAL_URL_FOR_ANDROID_EMULATOR: 'http://10.0.2.2:3001', //SOMETHING LIKE THIS REFER REACT NATIVE ERROR DOC
    LOCAL_URL_FOR_IOS_SIMULATOR: 'http://localhost:3001'
}

export default urls